name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: '30 9 * * 2'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: scorecard-${{ github.ref }}
  cancel-in-progress: false

jobs:
  scorecard:
    name: Scorecard
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Run Scorecard
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: scorecard.json
          results_format: json
          publish_results: true
